package net.github.andriimartynov.browscap

case class UserAgentInfo(
                          userAgentString: String = "",
                          propertyName: String = "",
                          isMasterParent: Boolean = false,
                          isLiteMode: Boolean = false,
                          parent: String = "",
                          comment: String = "",
                          browser: String = "",
                          browserType: String = "",
                          browserBits: String = "",
                          browserMaker: String = "",
                          browserModus: String = "",
                          version: String = "",
                          majorVersion: String = "",
                          minorVersion: String = "",
                          platform: String = "",
                          platformVersion: String = "",
                          platformDescription: String = "",
                          platformBits: String = "",
                          platformMaker: String = "",
                          isSyndicationReader: Boolean = false,
                          isFake: Boolean = false,
                          isAnonymized: Boolean = false,
                          isModified: Boolean = false,
                          cssVersion: String = "",
                          deviceName: String = "",
                          deviceMaker: String = "",
                          deviceType: String = "",
                          devicePointingMethod: String = "",
                          deviceCodeName: String = "",
                          deviceBrandName: String = "",
                          renderingEngineName: String = "",
                          renderingEngineVersion: String = "",
                          renderingEngineDescription: String = "",
                          renderingEngineMaker: String = ""
                        )
